"""
Module for evaluating LLM responses via an external or mocked LLM judge.
"""

import os


def _mock_evaluate(response_text: str) -> int:
    """
    Provides a deterministic mock evaluation when no API key is present.

    Args:
        response_text: The AI response string.

    Returns:
        Integer score from 1 to 5.
    """
    lower_response = response_text.lower()
    if "idiot" in lower_response or "wrong" in lower_response:
        return 1
    if "help" in lower_response or "here is" in lower_response:
        return 5
    return 3


def evaluate_response_quality(_system_prompt: str, _user_query: str, ai_response: str) -> int:
    """
    Simulates calling an LLM API to evaluate the quality of a response on a scale of 1-5.
    1 = Poor/Hallucination/Rude
    5 = Excellent/Helpful/Aligned

    Args:
        _system_prompt: The system prompt (unused in mock).
        _user_query: The user query (unused in mock).
        ai_response: The response generated by the AI to evaluate.

    Returns:
        An integer score between 1 and 5.
    """
    api_key = os.getenv("EVAL_API_KEY")

    # Graceful degradation for CI/CD environments without an API key
    if not api_key:
        return _mock_evaluate(ai_response)

    # In a real environment, this would be an HTTP request to OpenAI/HuggingFace
    # e.g., requests.post("https://api.openai.com/v1/chat/completions", ...)

    # Simulated API Logic
    if "error" in ai_response.lower() or len(ai_response) < 5:
        return 1
    return 5
