direction: right

IdealUser: "[Ideal Case] End User Data"
IdealUser.style.fill: "#0d1322"
IdealUser.style.stroke: "#ff0000"
IdealUser.style.stroke-dash: 5

Kaggle: "[Actual] Kaggle Dataset (CSV)"
Kaggle.style.fill: "#0d1322"
Kaggle.style.stroke: "#a020f0"

DuckDB: "Embedded OLAP Engine"
DuckDB.style.fill: "#0d1322"
DuckDB.style.stroke: "#57f1db"

FastAPI: "Analytical Backend"
FastAPI.style.fill: "#0d1322"
FastAPI.style.stroke: "#a020f0"

Browser: "Tailwind Dashboard"
Browser.style.fill: "#0d1322"
Browser.style.stroke: "#57f1db"

IdealUser -> Kaggle: "Replaced by (for Hackathon)" {
  style: {
    stroke-dash: 5
  }
}
Kaggle -> DuckDB: "Data Ingestion (read_csv_auto)"
DuckDB -> FastAPI: "Aggregated Metrics"
FastAPI -> Browser: "JSON Responses (/api/stats/*)"
